name: build and test
on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
env:
  DOTNET_VERSION: '5.0.x'
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: |
        dotnet restore CanWeFixIt/CanWeFixIt.sln
        dotnet restore YesWeCan/YesWeCan.sln
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore CanWeFixIt/CanWeFixIt.sln
        dotnet build --configuration Release --no-restore YesWeCan/YesWeCan.sln
    - name: Test
      run: |
        cd CanWeFixIt
        dotnet test --no-restore --verbosity normal